DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'week_day') THEN
    CREATE TYPE week_day AS ENUM (
      'Monday',
      'Tuesday',
      'Wednesday',
      'Thursday',
      'Friday',
      'Saturday',
      'Sunday'
    );
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS coaches (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE,
  speciality VARCHAR(160) NOT NULL,
  image_url TEXT NOT NULL,
  phone VARCHAR(40),
  email VARCHAR(120),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS coach_schedule (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  coach_id INTEGER NOT NULL REFERENCES coaches(id) ON DELETE CASCADE,
  day_name week_day NOT NULL,
  start_time TIME NOT NULL,
  end_time TIME NOT NULL,
  class_name VARCHAR(120) NOT NULL,
  duration_minutes INTEGER NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE (coach_id, day_name, start_time, end_time, class_name)
);

ALTER TABLE coaches
  ALTER COLUMN image_url TYPE TEXT;

INSERT INTO coaches (name, speciality, image_url, phone, email) VALUES
  ('Maha', 'Body Combat / ABS / Cross Training / Step', '/assets/photos/LOGo.png', '+216 24 000 103', 'maha@samuraigym.tn'),
  ('Nourhen', 'Gymnastique / Kung Fu / Step / Cardio', '/assets/photos/Coach Nourhen.png', '+216 24 000 104', 'nourhen@samuraigym.tn'),
  ('Siwar', 'Cardio / Step / Tabata', '/assets/photos/LOGo.png', '+216 24 000 102', 'siwar@samuraigym.tn'),
  ('Ahlem', 'Taekwondo', '/assets/photos/LOGo.png', '+216 24 000 105', 'ahlem@samuraigym.tn'),
  ('Med Jaber', 'Boxe', '/assets/photos/LOGo.png', '+216 24 000 106', 'med.jaber@samuraigym.tn'),
  ('Ahmed', 'Cross Training', '/assets/photos/Ahmed coach.png', '+216 24 000 107', 'ahmed@samuraigym.tn')
ON CONFLICT (name) DO UPDATE SET
  speciality = EXCLUDED.speciality,
  image_url = EXCLUDED.image_url,
  phone = EXCLUDED.phone,
  email = EXCLUDED.email,
  updated_at = NOW();

INSERT INTO coach_schedule (coach_id, day_name, start_time, end_time, class_name, duration_minutes)
SELECT id, 'Monday'::week_day, '08:00:00'::time, '09:00:00'::time, 'Body Combat', 60 FROM coaches WHERE name = 'Maha'
UNION ALL SELECT id, 'Wednesday'::week_day, '08:00:00'::time, '09:00:00'::time, 'ABS', 60 FROM coaches WHERE name = 'Maha'
UNION ALL SELECT id, 'Friday'::week_day, '08:00:00'::time, '09:00:00'::time, 'Cross Training', 60 FROM coaches WHERE name = 'Maha'
UNION ALL SELECT id, 'Monday'::week_day, '17:00:00'::time, '18:00:00'::time, 'Body Combat', 60 FROM coaches WHERE name = 'Maha'
UNION ALL SELECT id, 'Wednesday'::week_day, '17:00:00'::time, '18:00:00'::time, 'ABS', 60 FROM coaches WHERE name = 'Maha'
UNION ALL SELECT id, 'Saturday'::week_day, '09:00:00'::time, '10:00:00'::time, 'Step', 60 FROM coaches WHERE name = 'Maha'
UNION ALL SELECT id, 'Tuesday'::week_day, '09:00:00'::time, '10:00:00'::time, 'Gymnastique', 60 FROM coaches WHERE name = 'Nourhen'
UNION ALL SELECT id, 'Thursday'::week_day, '09:00:00'::time, '10:00:00'::time, 'Gymnastique', 60 FROM coaches WHERE name = 'Nourhen'
UNION ALL SELECT id, 'Sunday'::week_day, '09:00:00'::time, '10:00:00'::time, 'Gymnastique', 60 FROM coaches WHERE name = 'Nourhen'
UNION ALL SELECT id, 'Tuesday'::week_day, '10:30:00'::time, '12:00:00'::time, 'Kung Fu', 90 FROM coaches WHERE name = 'Nourhen'
UNION ALL SELECT id, 'Thursday'::week_day, '10:30:00'::time, '12:00:00'::time, 'Kung Fu', 90 FROM coaches WHERE name = 'Nourhen'
UNION ALL SELECT id, 'Sunday'::week_day, '10:30:00'::time, '12:00:00'::time, 'Kung Fu', 90 FROM coaches WHERE name = 'Nourhen'
UNION ALL SELECT id, 'Monday'::week_day, '18:00:00'::time, '19:00:00'::time, 'Step', 60 FROM coaches WHERE name = 'Nourhen'
UNION ALL SELECT id, 'Tuesday'::week_day, '20:00:00'::time, '21:00:00'::time, 'Renforcement', 60 FROM coaches WHERE name = 'Nourhen'
UNION ALL SELECT id, 'Thursday'::week_day, '20:00:00'::time, '21:00:00'::time, 'Circuit Training', 60 FROM coaches WHERE name = 'Nourhen'
UNION ALL SELECT id, 'Friday'::week_day, '17:00:00'::time, '18:00:00'::time, 'ABS', 60 FROM coaches WHERE name = 'Nourhen'
UNION ALL SELECT id, 'Saturday'::week_day, '19:00:00'::time, '20:00:00'::time, 'Cardio', 60 FROM coaches WHERE name = 'Nourhen'
UNION ALL SELECT id, 'Sunday'::week_day, '08:00:00'::time, '09:00:00'::time, 'Musculation', 60 FROM coaches WHERE name = 'Nourhen'
UNION ALL SELECT id, 'Monday'::week_day, '10:00:00'::time, '11:00:00'::time, 'Cardio', 60 FROM coaches WHERE name = 'Siwar'
UNION ALL SELECT id, 'Wednesday'::week_day, '10:00:00'::time, '11:00:00'::time, 'Step', 60 FROM coaches WHERE name = 'Siwar'
UNION ALL SELECT id, 'Friday'::week_day, '10:00:00'::time, '11:00:00'::time, 'Tabata', 60 FROM coaches WHERE name = 'Siwar'
UNION ALL SELECT id, 'Tuesday'::week_day, '18:30:00'::time, '20:00:00'::time, 'Taekwondo', 90 FROM coaches WHERE name = 'Ahlem'
UNION ALL SELECT id, 'Thursday'::week_day, '18:30:00'::time, '20:00:00'::time, 'Taekwondo', 90 FROM coaches WHERE name = 'Ahlem'
UNION ALL SELECT id, 'Saturday'::week_day, '10:30:00'::time, '12:00:00'::time, 'Taekwondo', 90 FROM coaches WHERE name = 'Ahlem'
UNION ALL SELECT id, 'Monday'::week_day, '19:00:00'::time, '20:00:00'::time, 'Boxe', 60 FROM coaches WHERE name = 'Med Jaber'
UNION ALL SELECT id, 'Wednesday'::week_day, '18:30:00'::time, '20:00:00'::time, 'Boxe', 90 FROM coaches WHERE name = 'Med Jaber'
UNION ALL SELECT id, 'Friday'::week_day, '18:30:00'::time, '20:00:00'::time, 'Boxe', 90 FROM coaches WHERE name = 'Med Jaber'
UNION ALL SELECT id, 'Monday'::week_day, '20:30:00'::time, '21:30:00'::time, 'Cross Training', 60 FROM coaches WHERE name = 'Ahmed'
UNION ALL SELECT id, 'Wednesday'::week_day, '20:00:00'::time, '21:00:00'::time, 'Cross Training', 60 FROM coaches WHERE name = 'Ahmed'
UNION ALL SELECT id, 'Friday'::week_day, '20:00:00'::time, '21:00:00'::time, 'Cross Training', 60 FROM coaches WHERE name = 'Ahmed'
ON CONFLICT (coach_id, day_name, start_time, end_time, class_name) DO UPDATE SET
  duration_minutes = EXCLUDED.duration_minutes;

CREATE INDEX IF NOT EXISTS idx_coach_schedule_day_time
  ON coach_schedule (day_name, start_time, end_time);

CREATE INDEX IF NOT EXISTS idx_coach_schedule_coach
  ON coach_schedule (coach_id);

ALTER TABLE coaches ENABLE ROW LEVEL SECURITY;
ALTER TABLE coach_schedule ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read coaches" ON coaches;
DROP POLICY IF EXISTS "Allow public read coach schedule" ON coach_schedule;
DROP POLICY IF EXISTS "Allow public write coaches" ON coaches;
DROP POLICY IF EXISTS "Allow public write coach schedule" ON coach_schedule;

CREATE POLICY "Allow public read coaches"
  ON coaches
  FOR SELECT
  USING (true);

CREATE POLICY "Allow public read coach schedule"
  ON coach_schedule
  FOR SELECT
  USING (true);

CREATE POLICY "Allow public write coaches"
  ON coaches
  FOR ALL
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Allow public write coach schedule"
  ON coach_schedule
  FOR ALL
  USING (true)
  WITH CHECK (true);
